version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: ec2-user
  Install:
    - location: scripts/install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: scripts/validate-service.sh
      timeout: 300
      runas: ec2-user
